### PR TITLE
Fix some findings in the onboarding / getting started process

### PR DESCRIPTION
**Pull request by mpanne**
After running the application locally for the first time I figured out small issues during getting started which I address with this PR. Added a docker-compose file for the local database and updated the readme.

### CODE REVIEW

**Review by frederike-ramin — APPROVED** [review]
Love it. Thanks for caring for the Readme. 👍

**Comment by frederike-ramin** [comment]
Btw: Please don't merge yet, I think Shahrooz has a better overview over the current Prisma Verisons and when to upgrade what.

**Review by shrzaf — CHANGES_REQUESTED** [review]
Hi Merlin, thanks for the review :)

1. `prisma migrate dev` was indeed missing in the readme. Thanks for noticing! We can also get rid of the instruction to run `prisma generate` since `prisma mgirate dev` takes care of that part already.
2.  The fact that we do not include a docker-compose for a local postgres was intentional on our part. First, everybody has their own preferences when it comes to setting up a local db server (some pull and set up the docker image manually, others using docker-compose, yet others use a native installation). Second, it is a trivial enough task, at least for the seniority level of the engineers building the app, and if it's not, we're more than happy to help any new team member set it up (the readme mentions the fact that a running postgres server is required and how to configure the app to use it, but not how to set it up). Third, it's another file that we must maintain and we'd like to avoid that if we can.
3. About the prisma upgrade: we have our own process for upgrading dependencies especially when it comes to more failure-prone upgrades such as the one in this PR. Also we mainly do it via dependabot PRs.

My suggestion is therefore to either leave the readme modification in the PR and revert everything else, or close the PR and we would gladly take over modifying the readme.

**Comment by mpanne** [comment]
@shrzaf Thank you for your detailed feedback! Sorry for adding so much without knowing your processes. I will close this PR since only the one line in the README is left. ;)

**Pull request closed without merging**
